# Generated by Django 4.0.6 on 2022-07-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=300)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
